language: go
go:
    - 1.9
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
install:
    - go get github.com/lu-ping/kcptun/client
    - go get github.com/lu-ping/kcptun/server
before_script:
script:
    - cd $HOME/gopath/src/github.com/lu-ping/kcptun/client
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - cd $HOME/gopath/src/github.com/lu-ping/kcptun/server
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - exit 0
